export const COUNT_INCREMENT = 'COUNT_INCREMENT'
export const COUNT_INCREMENT_SUCCESS = 'COUNT_INCREMENT_SUCCESS'
export const COUNT_DECREMENT = 'COUNT_DECREMENT'
export const COUNT_DECREMENT_SUCCESS = 'COUNT_DECREMENT_SUCCESS'
export const COUNT_INCREMENT_NUMBER = 'COUNT_INCREMENT_NUMBER'
export const COUNT_INCREMENT_NUMBER_SUCCESS = 'COUNT_INCREMENT_NUMBER_SUCCESS'
export const COUNT_DECREMENT_NUMBER = 'COUNT_DECREMENT_NUMBER'
export const COUNT_DECREMENT_NUMBER_SUCCESS = 'COUNT_DECREMENT_NUMBER_SUCCESS'


export const CREATE_TODO = 'CREATE_TODO'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'


export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'
